Ignore npm install failure only for 0.12
Revert "Use npm 2.15.11 with node 0.12"

This reverts commit 9503b5cc6b5b9a665f6d07d4090327a4d5e09cae.
Revert "Log npm-debug.log after failure"

This reverts commit 412ce63c5e79cc457c5010123e4ac430bb9f7ea9.
Remove ls attempt


Ls purported npm-debug.log location and ignore npm install failure


Attempt to cat npm-debug.log after install failure


Log npm-debug.log after failure


Use npm 2.15.11 with node 0.12

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -77,8 +77,19 @@ before_install:
       export JOBS=4;
     fi
 
+# node 0.12 is sometimes failing
+# with a "Callback called more than once" error
+# Despite that error, it seems like modules do get installed correctly,
+# and the rest of the build proceeds as normal.
+# So we ignore that error, just for node 0.12
+# If npm install ever fails in a more significant way,
+# the rest of the build should hopefully fail anyway.
 install:
-  - npm install
+  - if [[ $NODE_VERSION == "0.12" ]]; then
+      npm install || true;
+    else
+      npm install;
+    fi
 
 # This is a random private key used purely for testing.
 before_script:
